<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\RawStats;
use App\ProcessedStats;
use App\TeamStats;

class ProcessTeamStats extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'team:process';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Process everyones raw stats together to generate their team stats';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $bar = $this->output->createProgressBar(4);
        //Define global variables
        $emails_july = null;
        $emails_august = null;
        $emails_september = null;
        $emails_october = null;
        $emails_november = null;
        $emails_december = null;
        $emails_january = null;
        $emails_february = null;
        $emails_march = null;
        $emails_april = null;
        $emails_may = null;
        $emails_june = null;
        $calls_inbound_july = null;
        $calls_inbound_august = null;
        $calls_inbound_september = null;
        $calls_inbound_october = null;
        $calls_inbound_november = null;
        $calls_inbound_december = null;
        $calls_inbound_january = null;
        $calls_inbound_february = null;
        $calls_inbound_march = null;
        $calls_inbound_april = null;
        $calls_inbound_may = null;
        $calls_inbound_june = null;
        $calls_outbound_july = null;
        $calls_outbound_august = null;
        $calls_outbound_september = null;
        $calls_outbound_october = null;
        $calls_outbound_november = null;
        $calls_outbound_december = null;
        $calls_outbound_january = null;
        $calls_outbound_february = null;
        $calls_outbound_march = null;
        $calls_outbound_april = null;
        $calls_outbound_may = null;
        $calls_outbound_june = null;
        $calls_january_total = null;
        $calls_february_total = null;
        $calls_march_total = null;
        $calls_april_total = null;
        $calls_may_total = null;
        $calls_june_total = null;
        $calls_july_total = null;
        $calls_august_total = null;
        $calls_september_total = null;
        $calls_october_total = null;
        $calls_november_total = null;
        $calls_december_total = null;
        $output_july = null;
        $output_august = null;
        $output_september = null;
        $output_october = null;
        $output_november = null;
        $output_december = null;
        $output_january = null;
        $output_february = null;
        $output_march = null;
        $output_april = null;
        $output_may = null;
        $output_june = null;
        $quality_july = null;
        $quality_august = null;
        $quality_september = null;
        $quality_october = null;
        $quality_november = null;
        $quality_december = null;
        $quality_january = null;
        $quality_february = null;
        $quality_march = null;
        $quality_april = null;
        $quality_may = null;
        $quality_june = null;

        //Day Crew
        $daycrewrawstats = RawStats::where('role_id', '=', 1)->get();
        foreach ($daycrewrawstats as $raw_stats)
        {
            $emails_july += $raw_stats->emails_july;
            $emails_august += $raw_stats->emails_august;
            $emails_september += $raw_stats->emails_september;
            $emails_october += $raw_stats->emails_october;
            $emails_november += $raw_stats->emails_november;
            $emails_december += $raw_stats->emails_december;
            $emails_january += $raw_stats->emails_january;
            $emails_february += $raw_stats->emails_february;
            $emails_march += $raw_stats->emails_march;
            $emails_april += $raw_stats->emails_april;
            $emails_may += $raw_stats->emails_may;
            $emails_june += $raw_stats->emails_june;
            $calls_inbound_july += $raw_stats->calls_inbound_july;
            $calls_inbound_august += $raw_stats->calls_inbound_august;
            $calls_inbound_september += $raw_stats->calls_inbound_september;
            $calls_inbound_october += $raw_stats->calls_inbound_october;
            $calls_inbound_november += $raw_stats->calls_inbound_november;
            $calls_inbound_december += $raw_stats->calls_inbound_december;
            $calls_inbound_january += $raw_stats->calls_inbound_january;
            $calls_inbound_february += $raw_stats->calls_inbound_february;
            $calls_inbound_march += $raw_stats->calls_inbound_march;
            $calls_inbound_april += $raw_stats->calls_inbound_april;
            $calls_inbound_may += $raw_stats->calls_inbound_may;
            $calls_inbound_june += $raw_stats->calls_inbound_june;
            $calls_outbound_july += $raw_stats->calls_outbound_july;
            $calls_outbound_august += $raw_stats->calls_outbound_august;
            $calls_outbound_september += $raw_stats->calls_outbound_september;
            $calls_outbound_october += $raw_stats->calls_outbound_october;
            $calls_outbound_november += $raw_stats->calls_outbound_november;
            $calls_outbound_december += $raw_stats->calls_outbound_december;
            $calls_outbound_january += $raw_stats->calls_outbound_january;
            $calls_outbound_february += $raw_stats->calls_outbound_february;
            $calls_outbound_march += $raw_stats->calls_outbound_march;
            $calls_outbound_april += $raw_stats->calls_outbound_april;
            $calls_outbound_may += $raw_stats->calls_outbound_may;
            $calls_outbound_june += $raw_stats->calls_outbound_june;
            $calls_january_total += $calls_inbound_january + $calls_outbound_january;
            $calls_february_total += $calls_inbound_february + $calls_outbound_february;
            $calls_march_total += $calls_inbound_march + $calls_outbound_march;
            $calls_april_total += $calls_inbound_april + $calls_outbound_april;
            $calls_may_total += $calls_inbound_may + $calls_outbound_may;
            $calls_june_total += $calls_inbound_june + $calls_outbound_june;
            $calls_july_total += $calls_inbound_july + $calls_outbound_july;
            $calls_august_total += $calls_inbound_august + $calls_outbound_august;
            $calls_september_total += $calls_inbound_september + $calls_outbound_september;
            $calls_october_total += $calls_inbound_october + $calls_outbound_october;
            $calls_november_total += $calls_inbound_november + $calls_outbound_november;
            $calls_december_total += $calls_inbound_december + $calls_outbound_december;
            $output_july += $raw_stats->output_july;
            $output_august += $raw_stats->output_august;
            $output_september += $raw_stats->output_september;
            $output_october += $raw_stats->output_october;
            $output_november += $raw_stats->output_november;
            $output_december += $raw_stats->output_december;
            $output_january += $raw_stats->output_january;
            $output_february += $raw_stats->output_february;
            $output_march += $raw_stats->output_march;
            $output_april += $raw_stats->output_april;
            $output_may += $raw_stats->output_may;
            $output_june += $raw_stats->output_june;
            $quality_july += $raw_stats->quality_july;
            $quality_august += $raw_stats->quality_august;
            $quality_september += $raw_stats->quality_september;
            $quality_october += $raw_stats->quality_october;
            $quality_november += $raw_stats->quality_november;
            $quality_december += $raw_stats->quality_december;
            $quality_january += $raw_stats->quality_january;
            $quality_february += $raw_stats->quality_february;
            $quality_march += $raw_stats->quality_march;
            $quality_april += $raw_stats->quality_april;
            $quality_may += $raw_stats->quality_may;
            $quality_june += $raw_stats->quality_june;
        }
        $daycrewteamstats = new TeamStats;
        //save all entries
        $daycrewteamstats->role_id = 1;
        $daycrewteamstats->emails_july = $emails_july;
        $daycrewteamstats->emails_august = $emails_august;
        $daycrewteamstats->emails_september = $emails_september;
        $daycrewteamstats->emails_october = $emails_october;
        $daycrewteamstats->emails_november = $emails_november;
        $daycrewteamstats->emails_december = $emails_december;
        $daycrewteamstats->emails_january = $emails_january;
        $daycrewteamstats->emails_february = $emails_february;
        $daycrewteamstats->emails_march = $emails_march;
        $daycrewteamstats->emails_april = $emails_april;
        $daycrewteamstats->emails_may = $emails_may;
        $daycrewteamstats->emails_june = $emails_june;
        $daycrewteamstats->calls_inbound_july = $calls_inbound_july;
        $daycrewteamstats->calls_inbound_august = $calls_inbound_august;
        $daycrewteamstats->calls_inbound_september = $calls_inbound_september;
        $daycrewteamstats->calls_inbound_october = $calls_inbound_october;
        $daycrewteamstats->calls_inbound_november = $calls_inbound_november;
        $daycrewteamstats->calls_inbound_december = $calls_inbound_december;
        $daycrewteamstats->calls_inbound_january = $calls_inbound_january;
        $daycrewteamstats->calls_inbound_february = $calls_inbound_february;
        $daycrewteamstats->calls_inbound_march = $calls_inbound_march;
        $daycrewteamstats->calls_inbound_april = $calls_inbound_april;
        $daycrewteamstats->calls_inbound_may = $calls_inbound_may;
        $daycrewteamstats->calls_inbound_june = $calls_inbound_june;
        $daycrewteamstats->calls_outbound_july = $calls_outbound_july;
        $daycrewteamstats->calls_outbound_august = $calls_outbound_august;
        $daycrewteamstats->calls_outbound_september = $calls_outbound_september;
        $daycrewteamstats->calls_outbound_october = $calls_outbound_october;
        $daycrewteamstats->calls_outbound_november = $calls_outbound_november;
        $daycrewteamstats->calls_outbound_december = $calls_outbound_december;
        $daycrewteamstats->calls_outbound_january = $calls_outbound_january;
        $daycrewteamstats->calls_outbound_february = $calls_outbound_february;
        $daycrewteamstats->calls_outbound_march = $calls_outbound_march;
        $daycrewteamstats->calls_outbound_april = $calls_outbound_april;
        $daycrewteamstats->calls_outbound_may = $calls_outbound_may;
        $daycrewteamstats->calls_outbound_june = $calls_outbound_june;
        $daycrewteamstats->calls_total_july = $calls_july_total;
        $daycrewteamstats->calls_total_august = $calls_august_total;
        $daycrewteamstats->calls_total_september = $calls_september_total;
        $daycrewteamstats->calls_total_october = $calls_october_total;
        $daycrewteamstats->calls_total_november = $calls_november_total;
        $daycrewteamstats->calls_total_december = $calls_december_total;
        $daycrewteamstats->calls_total_january = $calls_january_total;
        $daycrewteamstats->calls_total_february = $calls_february_total;
        $daycrewteamstats->calls_total_march = $calls_march_total;
        $daycrewteamstats->calls_total_april = $calls_april_total;
        $daycrewteamstats->calls_total_may = $calls_may_total;
        $daycrewteamstats->calls_total_june = $calls_june_total;
        $daycrewteamstats->save();
        $bar->advance();

        //Reset stats
        $emails_july = null;
        $emails_august = null;
        $emails_september = null;
        $emails_october = null;
        $emails_november = null;
        $emails_december = null;
        $emails_january = null;
        $emails_february = null;
        $emails_march = null;
        $emails_april = null;
        $emails_may = null;
        $emails_june = null;
        $calls_inbound_july = null;
        $calls_inbound_august = null;
        $calls_inbound_september = null;
        $calls_inbound_october = null;
        $calls_inbound_november = null;
        $calls_inbound_december = null;
        $calls_inbound_january = null;
        $calls_inbound_february = null;
        $calls_inbound_march = null;
        $calls_inbound_april = null;
        $calls_inbound_may = null;
        $calls_inbound_june = null;
        $calls_outbound_july = null;
        $calls_outbound_august = null;
        $calls_outbound_september = null;
        $calls_outbound_october = null;
        $calls_outbound_november = null;
        $calls_outbound_december = null;
        $calls_outbound_january = null;
        $calls_outbound_february = null;
        $calls_outbound_march = null;
        $calls_outbound_april = null;
        $calls_outbound_may = null;
        $calls_outbound_june = null;
        $calls_january_total = null;
        $calls_february_total = null;
        $calls_march_total = null;
        $calls_april_total = null;
        $calls_may_total = null;
        $calls_june_total = null;
        $calls_july_total = null;
        $calls_august_total = null;
        $calls_september_total = null;
        $calls_october_total = null;
        $calls_november_total = null;
        $calls_december_total = null;
        $output_july = null;
        $output_august = null;
        $output_september = null;
        $output_october = null;
        $output_november = null;
        $output_december = null;
        $output_january = null;
        $output_february = null;
        $output_march = null;
        $output_april = null;
        $output_may = null;
        $output_june = null;
        $quality_july = null;
        $quality_august = null;
        $quality_september = null;
        $quality_october = null;
        $quality_november = null;
        $quality_december = null;
        $quality_january = null;
        $quality_february = null;
        $quality_march = null;
        $quality_april = null;
        $quality_may = null;
        $quality_june = null;

        //Evening Crew One
        $eveningcrewonerawstats = RawStats::where('role_id', '=', 2)->get();
        foreach ($eveningcrewonerawstats as $raw_stats)
        {
            $emails_july += $raw_stats->emails_july;
            $emails_august += $raw_stats->emails_august;
            $emails_september += $raw_stats->emails_september;
            $emails_october += $raw_stats->emails_october;
            $emails_november += $raw_stats->emails_november;
            $emails_december += $raw_stats->emails_december;
            $emails_january += $raw_stats->emails_january;
            $emails_february += $raw_stats->emails_february;
            $emails_march += $raw_stats->emails_march;
            $emails_april += $raw_stats->emails_april;
            $emails_may += $raw_stats->emails_may;
            $emails_june += $raw_stats->emails_june;
            $calls_inbound_july += $raw_stats->calls_inbound_july;
            $calls_inbound_august += $raw_stats->calls_inbound_august;
            $calls_inbound_september += $raw_stats->calls_inbound_september;
            $calls_inbound_october += $raw_stats->calls_inbound_october;
            $calls_inbound_november += $raw_stats->calls_inbound_november;
            $calls_inbound_december += $raw_stats->calls_inbound_december;
            $calls_inbound_january += $raw_stats->calls_inbound_january;
            $calls_inbound_february += $raw_stats->calls_inbound_february;
            $calls_inbound_march += $raw_stats->calls_inbound_march;
            $calls_inbound_april += $raw_stats->calls_inbound_april;
            $calls_inbound_may += $raw_stats->calls_inbound_may;
            $calls_inbound_june += $raw_stats->calls_inbound_june;
            $calls_outbound_july += $raw_stats->calls_outbound_july;
            $calls_outbound_august += $raw_stats->calls_outbound_august;
            $calls_outbound_september += $raw_stats->calls_outbound_september;
            $calls_outbound_october += $raw_stats->calls_outbound_october;
            $calls_outbound_november += $raw_stats->calls_outbound_november;
            $calls_outbound_december += $raw_stats->calls_outbound_december;
            $calls_outbound_january += $raw_stats->calls_outbound_january;
            $calls_outbound_february += $raw_stats->calls_outbound_february;
            $calls_outbound_march += $raw_stats->calls_outbound_march;
            $calls_outbound_april += $raw_stats->calls_outbound_april;
            $calls_outbound_may += $raw_stats->calls_outbound_may;
            $calls_outbound_june += $raw_stats->calls_outbound_june;
            $calls_january_total += $calls_inbound_january + $calls_outbound_january;
            $calls_february_total += $calls_inbound_february + $calls_outbound_february;
            $calls_march_total += $calls_inbound_march + $calls_outbound_march;
            $calls_april_total += $calls_inbound_april + $calls_outbound_april;
            $calls_may_total += $calls_inbound_may + $calls_outbound_may;
            $calls_june_total += $calls_inbound_june + $calls_outbound_june;
            $calls_july_total += $calls_inbound_july + $calls_outbound_july;
            $calls_august_total += $calls_inbound_august + $calls_outbound_august;
            $calls_september_total += $calls_inbound_september + $calls_outbound_september;
            $calls_october_total += $calls_inbound_october + $calls_outbound_october;
            $calls_november_total += $calls_inbound_november + $calls_outbound_november;
            $calls_december_total += $calls_inbound_december + $calls_outbound_december;
            $output_july += $raw_stats->output_july;
            $output_august += $raw_stats->output_august;
            $output_september += $raw_stats->output_september;
            $output_october += $raw_stats->output_october;
            $output_november += $raw_stats->output_november;
            $output_december += $raw_stats->output_december;
            $output_january += $raw_stats->output_january;
            $output_february += $raw_stats->output_february;
            $output_march += $raw_stats->output_march;
            $output_april += $raw_stats->output_april;
            $output_may += $raw_stats->output_may;
            $output_june += $raw_stats->output_june;
            $quality_july += $raw_stats->quality_july;
            $quality_august += $raw_stats->quality_august;
            $quality_september += $raw_stats->quality_september;
            $quality_october += $raw_stats->quality_october;
            $quality_november += $raw_stats->quality_november;
            $quality_december += $raw_stats->quality_december;
            $quality_january += $raw_stats->quality_january;
            $quality_february += $raw_stats->quality_february;
            $quality_march += $raw_stats->quality_march;
            $quality_april += $raw_stats->quality_april;
            $quality_may += $raw_stats->quality_may;
            $quality_june += $raw_stats->quality_june;
        }
        $eveningcrewoneteamstats = new TeamStats;
        //save all entries
        $eveningcrewoneteamstats->role_id = 2;
        $eveningcrewoneteamstats->emails_july = $emails_july;
        $eveningcrewoneteamstats->emails_august = $emails_august;
        $eveningcrewoneteamstats->emails_september = $emails_september;
        $eveningcrewoneteamstats->emails_october = $emails_october;
        $eveningcrewoneteamstats->emails_november = $emails_november;
        $eveningcrewoneteamstats->emails_december = $emails_december;
        $eveningcrewoneteamstats->emails_january = $emails_january;
        $eveningcrewoneteamstats->emails_february = $emails_february;
        $eveningcrewoneteamstats->emails_march = $emails_march;
        $eveningcrewoneteamstats->emails_april = $emails_april;
        $eveningcrewoneteamstats->emails_may = $emails_may;
        $eveningcrewoneteamstats->emails_june = $emails_june;
        $eveningcrewoneteamstats->calls_inbound_july = $calls_inbound_july;
        $eveningcrewoneteamstats->calls_inbound_august = $calls_inbound_august;
        $eveningcrewoneteamstats->calls_inbound_september = $calls_inbound_september;
        $eveningcrewoneteamstats->calls_inbound_october = $calls_inbound_october;
        $eveningcrewoneteamstats->calls_inbound_november = $calls_inbound_november;
        $eveningcrewoneteamstats->calls_inbound_december = $calls_inbound_december;
        $eveningcrewoneteamstats->calls_inbound_january = $calls_inbound_january;
        $eveningcrewoneteamstats->calls_inbound_february = $calls_inbound_february;
        $eveningcrewoneteamstats->calls_inbound_march = $calls_inbound_march;
        $eveningcrewoneteamstats->calls_inbound_april = $calls_inbound_april;
        $eveningcrewoneteamstats->calls_inbound_may = $calls_inbound_may;
        $eveningcrewoneteamstats->calls_inbound_june = $calls_inbound_june;
        $eveningcrewoneteamstats->calls_outbound_july = $calls_outbound_july;
        $eveningcrewoneteamstats->calls_outbound_august = $calls_outbound_august;
        $eveningcrewoneteamstats->calls_outbound_september = $calls_outbound_september;
        $eveningcrewoneteamstats->calls_outbound_october = $calls_outbound_october;
        $eveningcrewoneteamstats->calls_outbound_november = $calls_outbound_november;
        $eveningcrewoneteamstats->calls_outbound_december = $calls_outbound_december;
        $eveningcrewoneteamstats->calls_outbound_january = $calls_outbound_january;
        $eveningcrewoneteamstats->calls_outbound_february = $calls_outbound_february;
        $eveningcrewoneteamstats->calls_outbound_march = $calls_outbound_march;
        $eveningcrewoneteamstats->calls_outbound_april = $calls_outbound_april;
        $eveningcrewoneteamstats->calls_outbound_may = $calls_outbound_may;
        $eveningcrewoneteamstats->calls_outbound_june = $calls_outbound_june;
        $eveningcrewoneteamstats->calls_total_july = $calls_july_total;
        $eveningcrewoneteamstats->calls_total_august = $calls_august_total;
        $eveningcrewoneteamstats->calls_total_september = $calls_september_total;
        $eveningcrewoneteamstats->calls_total_october = $calls_october_total;
        $eveningcrewoneteamstats->calls_total_november = $calls_november_total;
        $eveningcrewoneteamstats->calls_total_december = $calls_december_total;
        $eveningcrewoneteamstats->calls_total_january = $calls_january_total;
        $eveningcrewoneteamstats->calls_total_february = $calls_february_total;
        $eveningcrewoneteamstats->calls_total_march = $calls_march_total;
        $eveningcrewoneteamstats->calls_total_april = $calls_april_total;
        $eveningcrewoneteamstats->calls_total_may = $calls_may_total;
        $eveningcrewoneteamstats->calls_total_june = $calls_june_total;
        $eveningcrewoneteamstats->save();
        $bar->advance();

        //Reset stats
        $emails_july = null;
        $emails_august = null;
        $emails_september = null;
        $emails_october = null;
        $emails_november = null;
        $emails_december = null;
        $emails_january = null;
        $emails_february = null;
        $emails_march = null;
        $emails_april = null;
        $emails_may = null;
        $emails_june = null;
        $calls_inbound_july = null;
        $calls_inbound_august = null;
        $calls_inbound_september = null;
        $calls_inbound_october = null;
        $calls_inbound_november = null;
        $calls_inbound_december = null;
        $calls_inbound_january = null;
        $calls_inbound_february = null;
        $calls_inbound_march = null;
        $calls_inbound_april = null;
        $calls_inbound_may = null;
        $calls_inbound_june = null;
        $calls_outbound_july = null;
        $calls_outbound_august = null;
        $calls_outbound_september = null;
        $calls_outbound_october = null;
        $calls_outbound_november = null;
        $calls_outbound_december = null;
        $calls_outbound_january = null;
        $calls_outbound_february = null;
        $calls_outbound_march = null;
        $calls_outbound_april = null;
        $calls_outbound_may = null;
        $calls_outbound_june = null;
        $calls_january_total = null;
        $calls_february_total = null;
        $calls_march_total = null;
        $calls_april_total = null;
        $calls_may_total = null;
        $calls_june_total = null;
        $calls_july_total = null;
        $calls_august_total = null;
        $calls_september_total = null;
        $calls_october_total = null;
        $calls_november_total = null;
        $calls_december_total = null;
        $output_july = null;
        $output_august = null;
        $output_september = null;
        $output_october = null;
        $output_november = null;
        $output_december = null;
        $output_january = null;
        $output_february = null;
        $output_march = null;
        $output_april = null;
        $output_may = null;
        $output_june = null;
        $quality_july = null;
        $quality_august = null;
        $quality_september = null;
        $quality_october = null;
        $quality_november = null;
        $quality_december = null;
        $quality_january = null;
        $quality_february = null;
        $quality_march = null;
        $quality_april = null;
        $quality_may = null;
        $quality_june = null;

        //Evening Crew Two
        $eveningcrewtworawstats = RawStats::where('role_id', '=', 3)->get();
        foreach ($eveningcrewtworawstats as $raw_stats)
        {
            $emails_july += $raw_stats->emails_july;
            $emails_august += $raw_stats->emails_august;
            $emails_september += $raw_stats->emails_september;
            $emails_october += $raw_stats->emails_october;
            $emails_november += $raw_stats->emails_november;
            $emails_december += $raw_stats->emails_december;
            $emails_january += $raw_stats->emails_january;
            $emails_february += $raw_stats->emails_february;
            $emails_march += $raw_stats->emails_march;
            $emails_april += $raw_stats->emails_april;
            $emails_may += $raw_stats->emails_may;
            $emails_june += $raw_stats->emails_june;
            $calls_inbound_july += $raw_stats->calls_inbound_july;
            $calls_inbound_august += $raw_stats->calls_inbound_august;
            $calls_inbound_september += $raw_stats->calls_inbound_september;
            $calls_inbound_october += $raw_stats->calls_inbound_october;
            $calls_inbound_november += $raw_stats->calls_inbound_november;
            $calls_inbound_december += $raw_stats->calls_inbound_december;
            $calls_inbound_january += $raw_stats->calls_inbound_january;
            $calls_inbound_february += $raw_stats->calls_inbound_february;
            $calls_inbound_march += $raw_stats->calls_inbound_march;
            $calls_inbound_april += $raw_stats->calls_inbound_april;
            $calls_inbound_may += $raw_stats->calls_inbound_may;
            $calls_inbound_june += $raw_stats->calls_inbound_june;
            $calls_outbound_july += $raw_stats->calls_outbound_july;
            $calls_outbound_august += $raw_stats->calls_outbound_august;
            $calls_outbound_september += $raw_stats->calls_outbound_september;
            $calls_outbound_october += $raw_stats->calls_outbound_october;
            $calls_outbound_november += $raw_stats->calls_outbound_november;
            $calls_outbound_december += $raw_stats->calls_outbound_december;
            $calls_outbound_january += $raw_stats->calls_outbound_january;
            $calls_outbound_february += $raw_stats->calls_outbound_february;
            $calls_outbound_march += $raw_stats->calls_outbound_march;
            $calls_outbound_april += $raw_stats->calls_outbound_april;
            $calls_outbound_may += $raw_stats->calls_outbound_may;
            $calls_outbound_june += $raw_stats->calls_outbound_june;
            $calls_january_total += $calls_inbound_january + $calls_outbound_january;
            $calls_february_total += $calls_inbound_february + $calls_outbound_february;
            $calls_march_total += $calls_inbound_march + $calls_outbound_march;
            $calls_april_total += $calls_inbound_april + $calls_outbound_april;
            $calls_may_total += $calls_inbound_may + $calls_outbound_may;
            $calls_june_total += $calls_inbound_june + $calls_outbound_june;
            $calls_july_total += $calls_inbound_july + $calls_outbound_july;
            $calls_august_total += $calls_inbound_august + $calls_outbound_august;
            $calls_september_total += $calls_inbound_september + $calls_outbound_september;
            $calls_october_total += $calls_inbound_october + $calls_outbound_october;
            $calls_november_total += $calls_inbound_november + $calls_outbound_november;
            $calls_december_total += $calls_inbound_december + $calls_outbound_december;
            $output_july += $raw_stats->output_july;
            $output_august += $raw_stats->output_august;
            $output_september += $raw_stats->output_september;
            $output_october += $raw_stats->output_october;
            $output_november += $raw_stats->output_november;
            $output_december += $raw_stats->output_december;
            $output_january += $raw_stats->output_january;
            $output_february += $raw_stats->output_february;
            $output_march += $raw_stats->output_march;
            $output_april += $raw_stats->output_april;
            $output_may += $raw_stats->output_may;
            $output_june += $raw_stats->output_june;
            $quality_july += $raw_stats->quality_july;
            $quality_august += $raw_stats->quality_august;
            $quality_september += $raw_stats->quality_september;
            $quality_october += $raw_stats->quality_october;
            $quality_november += $raw_stats->quality_november;
            $quality_december += $raw_stats->quality_december;
            $quality_january += $raw_stats->quality_january;
            $quality_february += $raw_stats->quality_february;
            $quality_march += $raw_stats->quality_march;
            $quality_april += $raw_stats->quality_april;
            $quality_may += $raw_stats->quality_may;
            $quality_june += $raw_stats->quality_june;
        }
        $eveningcrewtwoteamstats = new TeamStats;
        //save all entries
        $eveningcrewtwoteamstats->role_id = 3;
        $eveningcrewtwoteamstats->emails_july = $emails_july;
        $eveningcrewtwoteamstats->emails_august = $emails_august;
        $eveningcrewtwoteamstats->emails_september = $emails_september;
        $eveningcrewtwoteamstats->emails_october = $emails_october;
        $eveningcrewtwoteamstats->emails_november = $emails_november;
        $eveningcrewtwoteamstats->emails_december = $emails_december;
        $eveningcrewtwoteamstats->emails_january = $emails_january;
        $eveningcrewtwoteamstats->emails_february = $emails_february;
        $eveningcrewtwoteamstats->emails_march = $emails_march;
        $eveningcrewtwoteamstats->emails_april = $emails_april;
        $eveningcrewtwoteamstats->emails_may = $emails_may;
        $eveningcrewtwoteamstats->emails_june = $emails_june;
        $eveningcrewtwoteamstats->calls_inbound_july = $calls_inbound_july;
        $eveningcrewtwoteamstats->calls_inbound_august = $calls_inbound_august;
        $eveningcrewtwoteamstats->calls_inbound_september = $calls_inbound_september;
        $eveningcrewtwoteamstats->calls_inbound_october = $calls_inbound_october;
        $eveningcrewtwoteamstats->calls_inbound_november = $calls_inbound_november;
        $eveningcrewtwoteamstats->calls_inbound_december = $calls_inbound_december;
        $eveningcrewtwoteamstats->calls_inbound_january = $calls_inbound_january;
        $eveningcrewtwoteamstats->calls_inbound_february = $calls_inbound_february;
        $eveningcrewtwoteamstats->calls_inbound_march = $calls_inbound_march;
        $eveningcrewtwoteamstats->calls_inbound_april = $calls_inbound_april;
        $eveningcrewtwoteamstats->calls_inbound_may = $calls_inbound_may;
        $eveningcrewtwoteamstats->calls_inbound_june = $calls_inbound_june;
        $eveningcrewtwoteamstats->calls_outbound_july = $calls_outbound_july;
        $eveningcrewtwoteamstats->calls_outbound_august = $calls_outbound_august;
        $eveningcrewtwoteamstats->calls_outbound_september = $calls_outbound_september;
        $eveningcrewtwoteamstats->calls_outbound_october = $calls_outbound_october;
        $eveningcrewtwoteamstats->calls_outbound_november = $calls_outbound_november;
        $eveningcrewtwoteamstats->calls_outbound_december = $calls_outbound_december;
        $eveningcrewtwoteamstats->calls_outbound_january = $calls_outbound_january;
        $eveningcrewtwoteamstats->calls_outbound_february = $calls_outbound_february;
        $eveningcrewtwoteamstats->calls_outbound_march = $calls_outbound_march;
        $eveningcrewtwoteamstats->calls_outbound_april = $calls_outbound_april;
        $eveningcrewtwoteamstats->calls_outbound_may = $calls_outbound_may;
        $eveningcrewtwoteamstats->calls_outbound_june = $calls_outbound_june;
        $eveningcrewtwoteamstats->calls_total_july = $calls_july_total;
        $eveningcrewtwoteamstats->calls_total_august = $calls_august_total;
        $eveningcrewtwoteamstats->calls_total_september = $calls_september_total;
        $eveningcrewtwoteamstats->calls_total_october = $calls_october_total;
        $eveningcrewtwoteamstats->calls_total_november = $calls_november_total;
        $eveningcrewtwoteamstats->calls_total_december = $calls_december_total;
        $eveningcrewtwoteamstats->calls_total_january = $calls_january_total;
        $eveningcrewtwoteamstats->calls_total_february = $calls_february_total;
        $eveningcrewtwoteamstats->calls_total_march = $calls_march_total;
        $eveningcrewtwoteamstats->calls_total_april = $calls_april_total;
        $eveningcrewtwoteamstats->calls_total_may = $calls_may_total;
        $eveningcrewtwoteamstats->calls_total_june = $calls_june_total;
        $eveningcrewtwoteamstats->save();
        $bar->advance();

        //Reset stats
        $emails_july = null;
        $emails_august = null;
        $emails_september = null;
        $emails_october = null;
        $emails_november = null;
        $emails_december = null;
        $emails_january = null;
        $emails_february = null;
        $emails_march = null;
        $emails_april = null;
        $emails_may = null;
        $emails_june = null;
        $calls_inbound_july = null;
        $calls_inbound_august = null;
        $calls_inbound_september = null;
        $calls_inbound_october = null;
        $calls_inbound_november = null;
        $calls_inbound_december = null;
        $calls_inbound_january = null;
        $calls_inbound_february = null;
        $calls_inbound_march = null;
        $calls_inbound_april = null;
        $calls_inbound_may = null;
        $calls_inbound_june = null;
        $calls_outbound_july = null;
        $calls_outbound_august = null;
        $calls_outbound_september = null;
        $calls_outbound_october = null;
        $calls_outbound_november = null;
        $calls_outbound_december = null;
        $calls_outbound_january = null;
        $calls_outbound_february = null;
        $calls_outbound_march = null;
        $calls_outbound_april = null;
        $calls_outbound_may = null;
        $calls_outbound_june = null;
        $calls_january_total = null;
        $calls_february_total = null;
        $calls_march_total = null;
        $calls_april_total = null;
        $calls_may_total = null;
        $calls_june_total = null;
        $calls_july_total = null;
        $calls_august_total = null;
        $calls_september_total = null;
        $calls_october_total = null;
        $calls_november_total = null;
        $calls_december_total = null;
        $output_july = null;
        $output_august = null;
        $output_september = null;
        $output_october = null;
        $output_november = null;
        $output_december = null;
        $output_january = null;
        $output_february = null;
        $output_march = null;
        $output_april = null;
        $output_may = null;
        $output_june = null;
        $quality_july = null;
        $quality_august = null;
        $quality_september = null;
        $quality_october = null;
        $quality_november = null;
        $quality_december = null;
        $quality_january = null;
        $quality_february = null;
        $quality_march = null;
        $quality_april = null;
        $quality_may = null;
        $quality_june = null;

        //Nightwalkers
        $nightwalkerrawstats = RawStats::where('role_id', '=', 4)->get();
        foreach ($nightwalkerrawstats as $raw_stats)
        {
            $emails_july += $raw_stats->emails_july;
            $emails_august += $raw_stats->emails_august;
            $emails_september += $raw_stats->emails_september;
            $emails_october += $raw_stats->emails_october;
            $emails_november += $raw_stats->emails_november;
            $emails_december += $raw_stats->emails_december;
            $emails_january += $raw_stats->emails_january;
            $emails_february += $raw_stats->emails_february;
            $emails_march += $raw_stats->emails_march;
            $emails_april += $raw_stats->emails_april;
            $emails_may += $raw_stats->emails_may;
            $emails_june += $raw_stats->emails_june;
            $calls_inbound_july += $raw_stats->calls_inbound_july;
            $calls_inbound_august += $raw_stats->calls_inbound_august;
            $calls_inbound_september += $raw_stats->calls_inbound_september;
            $calls_inbound_october += $raw_stats->calls_inbound_october;
            $calls_inbound_november += $raw_stats->calls_inbound_november;
            $calls_inbound_december += $raw_stats->calls_inbound_december;
            $calls_inbound_january += $raw_stats->calls_inbound_january;
            $calls_inbound_february += $raw_stats->calls_inbound_february;
            $calls_inbound_march += $raw_stats->calls_inbound_march;
            $calls_inbound_april += $raw_stats->calls_inbound_april;
            $calls_inbound_may += $raw_stats->calls_inbound_may;
            $calls_inbound_june += $raw_stats->calls_inbound_june;
            $calls_outbound_july += $raw_stats->calls_outbound_july;
            $calls_outbound_august += $raw_stats->calls_outbound_august;
            $calls_outbound_september += $raw_stats->calls_outbound_september;
            $calls_outbound_october += $raw_stats->calls_outbound_october;
            $calls_outbound_november += $raw_stats->calls_outbound_november;
            $calls_outbound_december += $raw_stats->calls_outbound_december;
            $calls_outbound_january += $raw_stats->calls_outbound_january;
            $calls_outbound_february += $raw_stats->calls_outbound_february;
            $calls_outbound_march += $raw_stats->calls_outbound_march;
            $calls_outbound_april += $raw_stats->calls_outbound_april;
            $calls_outbound_may += $raw_stats->calls_outbound_may;
            $calls_outbound_june += $raw_stats->calls_outbound_june;
            $calls_january_total += $calls_inbound_january + $calls_outbound_january;
            $calls_february_total += $calls_inbound_february + $calls_outbound_february;
            $calls_march_total += $calls_inbound_march + $calls_outbound_march;
            $calls_april_total += $calls_inbound_april + $calls_outbound_april;
            $calls_may_total += $calls_inbound_may + $calls_outbound_may;
            $calls_june_total += $calls_inbound_june + $calls_outbound_june;
            $calls_july_total += $calls_inbound_july + $calls_outbound_july;
            $calls_august_total += $calls_inbound_august + $calls_outbound_august;
            $calls_september_total += $calls_inbound_september + $calls_outbound_september;
            $calls_october_total += $calls_inbound_october + $calls_outbound_october;
            $calls_november_total += $calls_inbound_november + $calls_outbound_november;
            $calls_december_total += $calls_inbound_december + $calls_outbound_december;
            $output_july += $raw_stats->output_july;
            $output_august += $raw_stats->output_august;
            $output_september += $raw_stats->output_september;
            $output_october += $raw_stats->output_october;
            $output_november += $raw_stats->output_november;
            $output_december += $raw_stats->output_december;
            $output_january += $raw_stats->output_january;
            $output_february += $raw_stats->output_february;
            $output_march += $raw_stats->output_march;
            $output_april += $raw_stats->output_april;
            $output_may += $raw_stats->output_may;
            $output_june += $raw_stats->output_june;
            $quality_july += $raw_stats->quality_july;
            $quality_august += $raw_stats->quality_august;
            $quality_september += $raw_stats->quality_september;
            $quality_october += $raw_stats->quality_october;
            $quality_november += $raw_stats->quality_november;
            $quality_december += $raw_stats->quality_december;
            $quality_january += $raw_stats->quality_january;
            $quality_february += $raw_stats->quality_february;
            $quality_march += $raw_stats->quality_march;
            $quality_april += $raw_stats->quality_april;
            $quality_may += $raw_stats->quality_may;
            $quality_june += $raw_stats->quality_june;
        }
        $nightwalkerteamstats = new TeamStats;
        //save all entries
        $nightwalkerteamstats->role_id = 4;
        $nightwalkerteamstats->emails_july = $emails_july;
        $nightwalkerteamstats->emails_august = $emails_august;
        $nightwalkerteamstats->emails_september = $emails_september;
        $nightwalkerteamstats->emails_october = $emails_october;
        $nightwalkerteamstats->emails_november = $emails_november;
        $nightwalkerteamstats->emails_december = $emails_december;
        $nightwalkerteamstats->emails_january = $emails_january;
        $nightwalkerteamstats->emails_february = $emails_february;
        $nightwalkerteamstats->emails_march = $emails_march;
        $nightwalkerteamstats->emails_april = $emails_april;
        $nightwalkerteamstats->emails_may = $emails_may;
        $nightwalkerteamstats->emails_june = $emails_june;
        $nightwalkerteamstats->calls_inbound_july = $calls_inbound_july;
        $nightwalkerteamstats->calls_inbound_august = $calls_inbound_august;
        $nightwalkerteamstats->calls_inbound_september = $calls_inbound_september;
        $nightwalkerteamstats->calls_inbound_october = $calls_inbound_october;
        $nightwalkerteamstats->calls_inbound_november = $calls_inbound_november;
        $nightwalkerteamstats->calls_inbound_december = $calls_inbound_december;
        $nightwalkerteamstats->calls_inbound_january = $calls_inbound_january;
        $nightwalkerteamstats->calls_inbound_february = $calls_inbound_february;
        $nightwalkerteamstats->calls_inbound_march = $calls_inbound_march;
        $nightwalkerteamstats->calls_inbound_april = $calls_inbound_april;
        $nightwalkerteamstats->calls_inbound_may = $calls_inbound_may;
        $nightwalkerteamstats->calls_inbound_june = $calls_inbound_june;
        $nightwalkerteamstats->calls_outbound_july = $calls_outbound_july;
        $nightwalkerteamstats->calls_outbound_august = $calls_outbound_august;
        $nightwalkerteamstats->calls_outbound_september = $calls_outbound_september;
        $nightwalkerteamstats->calls_outbound_october = $calls_outbound_october;
        $nightwalkerteamstats->calls_outbound_november = $calls_outbound_november;
        $nightwalkerteamstats->calls_outbound_december = $calls_outbound_december;
        $nightwalkerteamstats->calls_outbound_january = $calls_outbound_january;
        $nightwalkerteamstats->calls_outbound_february = $calls_outbound_february;
        $nightwalkerteamstats->calls_outbound_march = $calls_outbound_march;
        $nightwalkerteamstats->calls_outbound_april = $calls_outbound_april;
        $nightwalkerteamstats->calls_outbound_may = $calls_outbound_may;
        $nightwalkerteamstats->calls_outbound_june = $calls_outbound_june;
        $nightwalkerteamstats->calls_total_july = $calls_july_total;
        $nightwalkerteamstats->calls_total_august = $calls_august_total;
        $nightwalkerteamstats->calls_total_september = $calls_september_total;
        $nightwalkerteamstats->calls_total_october = $calls_october_total;
        $nightwalkerteamstats->calls_total_november = $calls_november_total;
        $nightwalkerteamstats->calls_total_december = $calls_december_total;
        $nightwalkerteamstats->calls_total_january = $calls_january_total;
        $nightwalkerteamstats->calls_total_february = $calls_february_total;
        $nightwalkerteamstats->calls_total_march = $calls_march_total;
        $nightwalkerteamstats->calls_total_april = $calls_april_total;
        $nightwalkerteamstats->calls_total_may = $calls_may_total;
        $nightwalkerteamstats->calls_total_june = $calls_june_total;
        $nightwalkerteamstats->save();
        $bar->advance();

        $bar->finish();
        $this->info(' Completed!');

        $all_team_stats = TeamStats::all();
        $bar = $this->output->createProgressBar(count($all_team_stats));

        foreach ($all_team_stats as $team_stats)
        {
            $emails_july = $team_stats->emails_july;
            $emails_august = $team_stats->emails_august;
            $emails_september = $team_stats->emails_september;
            $emails_october = $team_stats->emails_october;
            $emails_november = $team_stats->emails_november;
            $emails_december = $team_stats->emails_december;
            $emails_january = $team_stats->emails_january;
            $emails_february = $team_stats->emails_february;
            $emails_march = $team_stats->emails_march;
            $emails_april = $team_stats->emails_april;
            $emails_may = $team_stats->emails_may;
            $emails_june = $team_stats->emails_june;
            $calls_inbound_july = $team_stats->calls_inbound_july;
            $calls_inbound_august = $team_stats->calls_inbound_august;
            $calls_inbound_september = $team_stats->calls_inbound_september;
            $calls_inbound_october = $team_stats->calls_inbound_october;
            $calls_inbound_november = $team_stats->calls_inbound_november;
            $calls_inbound_december = $team_stats->calls_inbound_december;
            $calls_inbound_january = $team_stats->calls_inbound_january;
            $calls_inbound_february = $team_stats->calls_inbound_february;
            $calls_inbound_march = $team_stats->calls_inbound_march;
            $calls_inbound_april = $team_stats->calls_inbound_april;
            $calls_inbound_may = $team_stats->calls_inbound_may;
            $calls_inbound_june = $team_stats->calls_inbound_june;
            $calls_outbound_july = $team_stats->calls_outbound_july;
            $calls_outbound_august = $team_stats->calls_outbound_august;
            $calls_outbound_september = $team_stats->calls_outbound_september;
            $calls_outbound_october = $team_stats->calls_outbound_october;
            $calls_outbound_november = $team_stats->calls_outbound_november;
            $calls_outbound_december = $team_stats->calls_outbound_december;
            $calls_outbound_january = $team_stats->calls_outbound_january;
            $calls_outbound_february = $team_stats->calls_outbound_february;
            $calls_outbound_march = $team_stats->calls_outbound_march;
            $calls_outbound_april = $team_stats->calls_outbound_april;
            $calls_outbound_may = $team_stats->calls_outbound_may;
            $calls_outbound_june = $team_stats->calls_outbound_june;
            $calls_january_total = $team_stats->calls_total_january;
            $calls_february_total = $team_stats->calls_total_february;
            $calls_march_total = $team_stats->calls_total_march;
            $calls_april_total = $team_stats->calls_total_april;
            $calls_may_total = $team_stats->calls_total_may;
            $calls_june_total = $team_stats->calls_total_june;
            $calls_july_total = $team_stats->calls_total_july;
            $calls_august_total = $team_stats->calls_total_august;
            $calls_september_total = $team_stats->calls_total_september;
            $calls_october_total = $team_stats->calls_total_october;
            $calls_november_total = $team_stats->calls_total_november;
            $calls_december_total = $team_stats->calls_total_december;

            //Total emails
            $total_emails = $emails_july + $emails_august + $emails_september + $emails_october + $emails_november + $emails_december + $emails_january + $emails_february + $emails_march + $emails_april + $emails_may + $emails_june;

            //Total calls inbound
            $total_calls_inbound = $calls_inbound_july + $calls_inbound_august + $calls_inbound_september + $calls_inbound_october + $calls_inbound_november + $calls_inbound_december + $calls_inbound_january + $calls_inbound_february + $calls_inbound_march + $calls_inbound_april + $calls_inbound_may + $calls_inbound_june;

            //Total calls outbound
            $total_calls_outbound = $calls_outbound_july + $calls_outbound_august + $calls_outbound_september + $calls_outbound_october + $calls_outbound_november + $calls_outbound_december + $calls_outbound_january + $calls_outbound_february + $calls_outbound_march + $calls_outbound_april + $calls_outbound_may + $calls_outbound_june;

            $best_email_month_array = array('January' => $emails_january, 'February' => $emails_february, 'March' => $emails_march, 'April' => $emails_april, 'May' => $emails_may, 'June' => $emails_june, 'July' => $emails_july, 'August' => $emails_august, 'September' => $emails_september, 'October' => $emails_october, 'November' => $emails_november, 'December' => $emails_december);
            arsort($best_email_month_array);
            $best_email_month = key($best_email_month_array);

            $email_q1 = $emails_july + $emails_august + $emails_september;
            $email_q2 = $emails_october + $emails_november + $emails_december;
            $email_q3 = $emails_january + $emails_february + $emails_march;
            $email_q4 = $emails_april + $emails_may + $emails_june;

            $best_email_quarter_array = array('Quarter 1' => $email_q1, 'Quarter 2' => $email_q2, 'Quarter 3' => $email_q3, 'Quarter 4' => $email_q4);
            arsort($best_email_quarter_array);
            $best_email_quarter = key($best_email_quarter_array);

            $best_call_month_array = array('January' => $calls_january_total, 'February' => $calls_february_total, 'March' => $calls_march_total, 'April' => $calls_april_total, 'May' => $calls_may_total, 'June' => $calls_june_total, 'July' => $calls_july_total, 'August' => $calls_august_total, 'September' => $calls_september_total, 'October' => $calls_october_total, 'November' => $calls_november_total, 'December' => $calls_december_total);
            arsort($best_call_month_array);
            $best_call_month = key($best_call_month_array);

            $calls_q1 = $calls_july_total + $calls_august_total + $calls_september_total;
            $calls_q2 = $calls_october_total + $calls_november_total + $calls_december_total;
            $calls_q3 = $calls_january_total + $calls_february_total + $calls_march_total;
            $calls_q4 = $calls_april_total + $calls_may_total + $calls_june_total;

            $best_call_quarter_array = array('Quarter 1' => $calls_q1, 'Quarter 2' => $calls_q2, 'Quarter 3' => $calls_q3, 'Quarter 4' => $calls_q4);
            arsort($best_call_quarter_array);
            $best_call_quarter = key($best_call_quarter_array);

            $processed_stats = TeamStats::find($team_stats->id);
            $processed_stats->emails = $total_emails;
            $processed_stats->calls_inbound = $total_calls_inbound;
            $processed_stats->calls_outbound = $total_calls_outbound;
            $processed_stats->best_email_month = $best_email_month;
            $processed_stats->best_email_quarter = $best_email_quarter;
            $processed_stats->best_call_month = $best_call_month;
            $processed_stats->best_call_quarter = $best_call_quarter;
            $processed_stats->save();

            $bar->advance();
        }

        $bar->finish();
        $this->info(' Best email/call months and quarters calculated.');
    }
}
